classes:
  beast:
    - DIAMOND_SWORD 1
    - IRON_AXE 1
    - APPLE 10
    - IRON_HELMET 1
    - IRON_CHESTPLATE 1
    - IRON_LEGGINGS 1
    - IRON_BOOTS 1
  scout:
    - STONE_SWORD 1
    - MAP 1
    - GOLDEN_APPLE 3
    - COOKED_CHICKEN 5
    - ENDER_PEARL 5
    - COOKED_BEEF 20
    - CHAINMAIL_HELMET 1
    - CHAINMAIL_CHESTPLATE 1
    - CHAINMAIL_LEGGINGS 1
    - CHAINMAIL_BOOTS 1
    - SADDLE 1
  archer:
    - BOW 1
    - ARROW 64
    - STONE_SWORD 1
    - MUSHROOM_SOUP 2
    - COOKED_CHICKEN 5
    - COOKED_BEEF 5
    - LEATHER_HELMET 1
    - LEATHER_CHESTPLATE 1
    - LEATHER_LEGGINGS 1
    - LEATHER_BOOTS 1
  jackofalltrades:
    - BOW 1
    - ARROW 16
    - IRON_SWORD 1
    - MUSHROOM_SOUP 5
    - BREAD 5
    - GRILLED_PORK 10
    - COOKED_FISH 10
    - GOLD_HELMET 1
    - CHAINMAIL_CHESTPLATE 1
    - LEATHER_LEGGINGS 1
    - IRON_BOOTS 1