name: Apocalypse
main: org.kaufer.matthew.ApocalypsePlugin.Apocalypse
version: 1.0.0
author: mjkaufer
commands:
    apocalypse:
        description: returns plugin info
permissions:
    Apocalypse.*:
        description: allows manual zombie-spawning and chest updating
        default: op